---
kind: pipeline
type: docker
name: osmscoutserver

workspace:
  base: /home/nemo/rpmbuild

steps:
  - name: download-artifacts
    image: rclone/rclone
    environment:
      RCLONE_S3_PROVIDER: Minio
      RCLONE_S3_ACCESS_KEY_ID:
        from_secret: s3_access_key
      RCLONE_S3_SECRET_ACCESS_KEY:
        from_secret: s3_secret_key
      RCLONE_S3_ENDPOINT:
        from_secret: s3_endpoint
    commands:
      - rclone copy :s3:cache/RPMS ./RPMS
  - name: pkg-osmscout-server
    image: coderus/sailfishos-platform-sdk
    user: root
    commands:
      - cp -R ~nemo/.scratchbox2/ /root
      - sb2 -R -t SailfishOS-3.4.0.22-armv7hl zypper -n in git libcurl-devel sqlite-devel cairo-devel harfbuzz-devel libjpeg-turbo-devel libpng-devel libtiff-devel libxml2-devel zlib libcurl protobuf-devel boost-devel boost-date-time boost-chrono boost-filesystem boost-iostreams boost-regex boost-system desktop-file-utils systemd-devel
      - sb2 -R -t SailfishOS-3.4.0.22-armv7hl rpm -i ./RPMS/armv7hl/*.rpm
      - sb2 -R -t SailfishOS-3.4.0.22-armv7hl rpmbuild -bb SPECS/osmserver.spec
      - sb2 -R -t SailfishOS-3.4.0.22-armv7hl cp -R /root/rpmbuild/RPMS/ ./
  - name: upload-artifacts
    image: rclone/rclone
    environment:
      RCLONE_S3_PROVIDER: Minio
      RCLONE_S3_ACCESS_KEY_ID:
        from_secret: s3_access_key
      RCLONE_S3_SECRET_ACCESS_KEY:
        from_secret: s3_secret_key
      RCLONE_S3_ENDPOINT:
        from_secret: s3_endpoint
    commands:
      - rclone copy ./RPMS :s3:cache/RPMS
---
kind: pipeline
type: docker
name: publish-to-github

workspace:
  base: /home/nemo/rpmbuild

steps:
  - name: download-artifacts
    image: rclone/rclone
    environment:
      RCLONE_S3_PROVIDER: Minio
      RCLONE_S3_ACCESS_KEY_ID:
        from_secret: s3_access_key
      RCLONE_S3_SECRET_ACCESS_KEY:
        from_secret: s3_secret_key
      RCLONE_S3_ENDPOINT:
        from_secret: s3_endpoint
    commands:
      - rclone copy :s3:cache/RPMS ./RPMS
  - name: publish-github-release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: release
      files: ./RPMS/armv7hl/*
      title: Build Artifacts
      when:
        event: tag
depends_on:
  - osmscoutserver
